### ISSUE TITLE
Crash when starting up

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/mpfb2#106]
From forum post: http://www.makehumancommunity.org/forum/viewtopic.php?f=22&t=22231&p=58879#p58860

```
[INFO ] mpfb.init ..............................: Build info 20230518
[INFO ] services.locationservice ...............: mh_user_dir is not explicitly set but autodiscovery is disabled
[INFO ] services.uiservice .....................: Rebuilding the list of available importer presets (for presets panel)
[INFO ] services.uiservice .....................: Rebuilding the list of available importer presets (for importer panel)Exception in module register(): C:\Users\User1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mpfb\__init__.py
Traceback (most recent call last):
File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\addon_utils.py", line 369, in enable
mod.register()
File "C:\Users\User1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mpfb\__init__.py", line 113, in register
import mpfb.ui
File "C:\Users\User1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mpfb\ui\__init__.py", line 17, in <module>
from mpfb.ui.newhuman import *
File "C:\Users\User1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mpfb\ui\newhuman\__init__.py", line 11, in <module>
from .frompresetspanel import MPFB_PT_From_Presets_Panel
File "C:\Users\User1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mpfb\ui\newhuman\frompresetspanel.py", line 15, in <module>
PRESETS_HUMAN_PROPERTIES = SceneConfigSet.from_definitions_in_json_directory(PRESETS_HUMAN_PROPERTIES_DIR, prefix="FPR_")
File "C:\Users\User1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mpfb\services\sceneconfigset.py", line 23, in from_definitions_in_json_directory
known_properties = BlenderConfigSet.get_definitions_in_json_directory(properties_dir)
File "C:\Users\User1\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mpfb\services\blenderconfigset.py", line 40, in get_definitions_in_json_directory
data = json.load(json_file)
File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\json\__init__.py", line 293, in load
return loads(fp.read(),
File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\json\__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\json\decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 12 column 5 (char 685)
```

**Comment by joepal1976** [comment]
Reported as solved on forums. Will assume it was a configuration issue, such as a missing or corrupt file.
