### ISSUE TITLE
Issues generating Rigify rig as well as applying Eyes from the asset library. Blender 4.0

### ISSUE THREAD

**Issue by SkinniestSpade** [makehumancommunity/mpfb2#157]
I am unable to generate Rigify rigs in Blender 4.0. I can generate standard rigs but adding eyes create errors. Same or more issues with the other builds as well.

### **When trying to add eyes to standard rig:**
Python: Traceback (most recent call last):
  File "C:\Users\abcbo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\mpfb\ui\assetlibrary\operators\loadlibraryclothes.py", line 78, in execute
    HumanService.add_mhclo_asset(
  File "C:\Users\abcbo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\mpfb\services\humanservice.py", line 408, in add_mhclo_asset
    NodeService.apply_node_tree_from_dict(blender_material.node_tree, node_tree_dict, True)
  File "C:\Users\abcbo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\mpfb\services\nodeservice.py", line 571, in apply_node_tree_from_dict
    NodeService._ensure_group_interfaces_exist(dict_with_node_tree)
  File "C:\Users\abcbo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\mpfb\services\nodeservice.py", line 555, in _ensure_group_interfaces_exist
    if not output_name in node_tree.outputs:
AttributeError: 'ShaderNodeTree' object has no attribute 'outputs'

### **When tryingto generate Rigify Rig:**
Python: Traceback (most recent call last):
  File "C:\Users\abcbo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\mpfb\ui\addrig\operators\addrigifyrig.py", line 45, in execute
    HumanService.add_builtin_rig(basemesh, "rigify." + rigify_rig, import_weights=import_weights, operator=self)
  File "C:\Users\abcbo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\mpfb\services\humanservice.py", line 1169, in add_builtin_rig
    armature_object = rig.create_armature_and_fit_to_basemesh()
  File "C:\Users\abcbo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\mpfb\entities\rig.py", line 200, in create_armature_and_fit_to_basemesh
    self.update_edit_bone_metadata()
  File "C:\Users\abcbo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\mpfb\entities\rig.py", line 376, in update_edit_bone_metadata
    bone.layers[i] = True
AttributeError: 'EditBone' object has no attribute 'layers'

### **When trying to force apply eyes to Rigify:**
Fit to body is enabled, but active object is not a base mesh

### **Platform and versions**
 - OS: Windows 10
 - Blender 4.0
 - MPFB Latest, November 16 2023. Download File was uploaded on November 14, 2023.

Thank You.

**Comment by joepal1976** [comment]
Just checking: Did you download the blender4 specific build? The main nightly build is still for 3.6. In order to get blender4 compatibility you need to download the file named "mpfb2-blender4-..." from http://files.makehumancommunity.org/plugins/

**Comment by SkinniestSpade** [comment]
Yes I made sure to download the latest Blender4 version of MPFB. I tried the latest as well as the one just labeled with the date. No luck.

**Comment by joepal1976** [comment]
Ok, I see the problem. The blender4 addon zip does not contain the blender4 branch, somehow it has switched back to the master branch...

I'm on it. I'll try to fix the build script and push out a new build tonight, but it might take until tomorrow's nightly build to propagate.

**Comment by joepal1976** [comment]
I've forced a new build now. The file names have the same date, but the contents should now be correct. 

Does the new blender4 build work for you?

**Comment by SkinniestSpade** [comment]
It works now thanks! I'm gonna play around with it a bit and see what happens.
