### ISSUE TITLE
Crash when converting game engine rig to rigify

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/mpfb2#210]
This was probably something which was missed in the blender 4 update. Need to investigate.

```
Error: Python: Traceback (most recent call last):
  File "/home/joepal/.config/blender/4.2/scripts/addons/mpfb/ui/rigify/operators/converttorigify.py", line 48, in execute
    helpers.convert_to_rigify(blender_object)
  File "/home/joepal/.config/blender/4.2/scripts/addons/mpfb/entities/rigging/rigifyhelpers/rigifyhelpers.py", line 72, in convert_to_rigify
    bpy.ops.pose.rigify_generate()
  File "/home/joepal/system/blender-4.2.0-linux-x64/4.2/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: No bone collections have UI buttons assigned - please check the Bone Collections UI sub-panel
```

**Comment by joepal1976** [comment]
Assumed to be working as intended.
