### ISSUE TITLE
Errors when creating human from scratch

### ISSUE THREAD

**Issue by Victor1266** [makehumancommunity/mpfb2#27]
Cant create human from scratch with some parameters 
![image](https://user-images.githubusercontent.com/18232879/163206036-4dfd221e-5d51-44ae-816b-aca815a272f5.png)

`Python: [ERROR] mpfb.init ..............................: Unhandled crash 
  File "C:\Users\vante\Documents\PycharmProjects\character_generator_3_1\blender\3.1\scripts\addons\mpfb\ui\newhuman\operators\createhuman.py", line 139, in execute
    basemesh = HumanService.create_human(
  File "C:\Users\vante\Documents\PycharmProjects\character_generator_3_1\blender\3.1\scripts\addons\mpfb\services\humanservice.py", line 996, in create_human
    TargetService.reapply_macro_details(basemesh)
  File "C:\Users\vante\Documents\PycharmProjects\character_generator_3_1\blender\3.1\scripts\addons\mpfb\services\targetservice.py", line 814, in reapply_macro_details
    for shape_key in basemesh.data.shape_keys.key_blocks:

'NoneType' object has no attribute 'key_blocks'

Traceback (most recent call last):
  File "C:\Users\vante\Documents\PycharmProjects\character_generator_3_1\blender\3.1\scripts\addons\mpfb\ui\newhuman\operators\createhuman.py", line 139, in execute
    basemesh = HumanService.create_human(
  File "C:\Users\vante\Documents\PycharmProjects\character_generator_3_1\blender\3.1\scripts\addons\mpfb\services\humanservice.py", line 996, in create_human
    TargetService.reapply_macro_details(basemesh)
  File "C:\Users\vante\Documents\PycharmProjects\character_generator_3_1\blender\3.1\scripts\addons\mpfb\services\targetservice.py", line 814, in reapply_macro_details
    for shape_key in basemesh.data.shape_keys.key_blocks:
AttributeError: 'NoneType' object has no attribute 'key_blocks'

location: <unknown location>:-1

`

**Comment by joepal1976** [comment]
Can confirm that this combination of settings crashes for me too. Investigations are pending.

**Comment by joepal1976** [comment]
I think this should fix the particular error with "child" age. Can you test and report back if it solves your problem?

The fix will appear in tomorrow's nightly build, if you don't want to run from source.
